# Generated by Django 5.2.1 on 2025-05-27 20:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(blank=True, max_length=255, null=True, verbose_name='Место выполнения')),
                ('action_time', models.TimeField(blank=True, null=True, verbose_name='Время выполнения')),
                ('action', models.CharField(default='default_value', max_length=255, verbose_name='Действие')),
                ('is_pleasant', models.BooleanField(default=False, verbose_name='Приятная привычка')),
                ('periodicity', models.PositiveIntegerField(blank=True, default=1, null=True, verbose_name='Периодичность выполнения')),
                ('reward', models.CharField(blank=True, max_length=255, null=True, verbose_name='Вознаграждение')),
                ('lead_time', models.PositiveIntegerField(blank=True, null=True, verbose_name='Продолжительность выполнения')),
                ('is_public', models.BooleanField(blank=True, default=False, null=True, verbose_name='Публичная привычка')),
                ('last_notice_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата последнего уведомления')),
                ('associated_habit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='habits.habit', verbose_name='Связанная привычка')),
            ],
            options={
                'verbose_name': 'Привычка',
                'verbose_name_plural': 'Привычки',
            },
        ),
    ]
