# Generated by Django 5.1.8 on 2025-04-15 16:43
import datetime
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='last_notification_date',
            field=models.DateField(default=datetime.date(2025, 4, 15),
                                   verbose_name='Дата последнего уведомления'),
        ),
    ]
