# Generated by Django 5.1.8 on 2025-04-15 16:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0003_habit_last_notification_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='last_notification_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата последнего уведомления'),
        ),
    ]
