# Generated by Django 4.2.21 on 2025-05-27 17:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0005_alter_habit_last_notification_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='last_notification_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата последнего уведомления'),
        ),
    ]
